config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :players

  resources :import, only: [:new] do
  	put :import_data, on: :collection
  end

  root 'players#index'
end

app/models/concerns/import_mz_data.rb
module ImportMzData
	def import name, data
		data.split("\r\n").each do |player_data|
			attributes_data = player_data.split("\t")

			player		= self.players.find_by(number: attributes_data[0], name: attributes_data[1])
			player	  ||= self.players.find_by(name: attributes_data[1])
			player	  ||= self.players.build
			attributes	= player.player_updates.build

			player.number	= attributes_data[0]
			player.name		= attributes_data[1]

			attributes.name		= name

			attributes.value	= attributes_data[2].gsub(' ', '').to_i
			attributes.salary	= attributes_data[3].gsub(' ', '').to_i
			attributes.age		= attributes_data[4]
			attributes.session	= attributes_data[5]

			attributes.speed			= attributes_data[8]
			attributes.stamina			= attributes_data[9]
			attributes.play_intelligence= attributes_data[10]
			attributes.passing			= attributes_data[11]
			attributes.shooting			= attributes_data[12]
			attributes.header			= attributes_data[13]
			attributes.keeping			= attributes_data[14]
			attributes.ball_control		= attributes_data[15]
			attributes.tackling			= attributes_data[16]
			attributes.cross_balls		= attributes_data[17]
			attributes.set_plays		= attributes_data[18]
			attributes.experience		= attributes_data[19]
			attributes.form				= attributes_data[20]

			player.save!

		end
	end
end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :player_updates

	belongs_to :user

	default_scope{ order(:number) }

	validates :user,	presence: true

	validates :number,	numericality: {greather_than_or_equal_to: 0, less_than: 2 ** 32, only_integer: true}
	validates :name,	presence: true, length: {maximum: 255}

	def attributes; @last_update ||= self.player_updates.last; end
	def updates; @updates ||= self.player_updates.map(&:name); end
end

app/models/player_data.rb
class PlayerData < ActiveRecord::Base
	belongs_to :player

	validates :player, presence: true

	validates :name, length: {maximum: 255}

	validates :value, :salary, :age, :session,
		numericality: {greather_than_or_equal_to: 0, less_than: 2 ** 32, only_integer: true}

	validates :speed, :stamina, :play_intelligence, :passing, :shooting, :header, :keeping, 
				:ball_control, :tackling, :cross_balls, :set_plays, :experience, :form,
		inclusion: 0..10
end

app/models/player_update.rb
class PlayerUpdate < ActiveRecord::Base
	belongs_to :player

	validates :player, presence: true

	validates :name, length: {maximum: 255}

	validates :value, :salary, :age, :session,
		numericality: {greather_than_or_equal_to: 0, less_than: 2 ** 32, only_integer: true}

	validates :speed, :stamina, :play_intelligence, :passing, :shooting, :header, :keeping, 
				:ball_control, :tackling, :cross_balls, :set_plays, :experience, :form,
		inclusion: 0..10
end

app/models/user.rb
class User < ActiveRecord::Base
	include ImportMzData

	# Include default devise modules. Others available are: :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

	has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	before_action :authenticate_user!
end

app/controllers/import_controller.rb
class ImportController < ApplicationController
	def new
	end

	def import_data
		if current_user.import(params[:name], params[:data])
			redirect_to players_path, notice: ''
		else
			redirect_to new_import_path, notice: ''
		end
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	def index
		@players = current_user.players
	end

	def show
		@players = current_user.players
		@player = @players.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/import/new.html.erb
<center>
	<%= form_tag '/import/import_data', method: :put do %>
		<%= label_tag 'Name' %>
		<%= text_field_tag :name %>
		<br/>
		<%= text_area_tag :data, nil, rows: 20, cols: 100 %>
		<br/>
		<%= submit_tag 'Import Data', class: 'button button-submit' %>
	<% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>MZ Player Evolution</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	<div class=toolbar>
		<%= link_to 'Players', players_path, class: 'button' %>
		<%= link_to 'Import MZ Data', new_import_path, class: 'button' %>
	</div>
<% end %>

<p class=notice><%= notice %></p>
<p class=alert><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/players/_index.html.erb
<table class=players>
	<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
		</tr>
	</thead>

	<tbody>
		<% @players.each do |player| %>
			<tr>
				<td style="text-align: center"><%= link_to player.number, player_path(player.id) %></td>
				<td><%= link_to player.name, player_path(player.id) %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/players/index.html.erb
<%= render 'index' %>

app/views/players/show.html.erb
<div style="display: inline-flex; width: 100%">

	<%= render 'index' %>

	<div style="padding: 1em; display: table; margin: auto;">

		<div class=player>

			<%= @player.number %> - <%= @player.name %>

			<br/>
			<br/>

			<table>
				<tr>
					<td>Value: <%= number_to_currency(@player.attributes.value) %></td>
					<td>Salary: <%= number_to_currency(@player.attributes.salary) %></td>
				</tr>
				<tr>
					<td>Age: <%= @player.attributes.age %></td>
					<td>Session: <%= @player.attributes.session %></td>
				</tr>
			</table>

			<br/>
			<div class=update-box>
				<%= select_tag :name, options_for_select(@player.updates, @player.updates.last) %>
				<%= label_tag '> Compare with >' %>
				<%= select_tag :name, options_for_select(@player.updates, @player.updates.last) %>
			</div>
			<br/>

			<table>
				<% [:speed, :stamina, :play_intelligence, :passing, :shooting, :header, :keeping, :ball_control, 
					:tackling, :cross_balls, :set_plays, :experience, :form].each do |attr| %>
					<tr>
						<td>
							<%= I18n.t(attr) %>
							<%= image_tag 'space.png' %>
						</td>
						<td>
							<% (1..@player.attributes.send(attr)).each do || %>
								<%= image_tag 'skill.png' %>
							<% end %>
							<% (@player.attributes.send(attr)..10).each do || %>
								<%= image_tag 'space.png' %>
							<% end if attr == :speed %>
						</td>
						<td>(<%= @player.attributes.send(attr) %>)</td>
					</tr>
				<% end %>
			</table>

		</div>

	</div>

</div>